### ISSUE TITLE
results summary file states failed cases as PASSED

### ISSUE THREAD

**Issue by okartau** [01org/DAFT#73]
In the file results-runtest.py.TIMESTAMP.log there is nicely formatted summary
of all tests with status. This is convenient file to use for getting counts in a CI system,
without parsing entire xml output (this is what Jenkins plugin does).
However, results-runtest.py.TIMESTAMP.log states all cases as PASSED
even if in reality some cases were FAIL.

This happens both in current daft, and also has happened in older times when we were still
using aft.

The code that writes summary, seems to be in oeqa/utils/decorators.py
        for (name, msg) in result.errors:
            if (self._testMethodName == str(name).split(' ')[0]) and (class_name in str(name).split(' ')[1]):
                local_log.results("Testcase "+str(test_case)+": ERROR")
                local_log.results("Testcase "+str(test_case)+":\n"+msg)
                passed = False

where there is three for-loops trying to match for error, failed or skipped status.
In case of no matches, PASSED will be used.
Seems there is a problem so that no matched get found even if case was FAILED,
and default PASSED is assigned at the end.

**Comment by okartau** [comment]
just realized to code I mentioned is not part of daft, but is
openembedded-core/meta/lib/oeqa/utils/decorators.py
so perhaps this is not daft issue at all

**Comment by skuusela** [comment]
@okartau I'm closing this issue as the problem has been tested to be in the file you mentioned and not in DAFT.
